language: php
php:
  - 7.1.14
  - 7.2
install:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader
before-script:
  - composer require php-coveralls/php-coveralls
script:
  - php vendor/bin/phpunit --coverage-clover clover.xml
after_script:
  - php vendor/bin/coveralls --coverage_clover=clover.xml -v
cache:
  directories:
    - $HOME/.composer/cache/files
script:
