language: php

php:
  - 7.1.15
  - 7.2.4

install:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader

before_script:
  - composer require php-coveralls/php-coveralls

script:
  - composer test-coverage

after_script:
  - php vendor/bin/php-coveralls --coverage_clover=clover.xml -v

cache:
  directories:
    - $HOME/.composer/cache/files
script:
