language: php
php:
  - 7.1.14
  - 7.2
install:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader
script:
  - composer test
cache:
  directories:
    - $HOME/.composer/cache/files
